/-
Copyright (c) 2026 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne
-/
module

public import MaynardZhang2026Complexity.MXJF2026.Setting
public import LeanMachineLearning.SequentialLearning.IonescuTulceaSpace
public import MaynardZhang2026Complexity.LeanMachineLearning.Online.Bandit.ChangeOfMeasure

/-!
# Lemma 6: change of measure at a stopping time for non-stationary bandits

On the trajectory space of an algorithm played against the non-stationary bandits `ν` and `ν'`,
`P_ν'(E) = E_ν[1_E exp(-L_σ)]` for every stopping time `σ` and event `E ∈ 𝓕_σ`, where `L_t` is
the log-likelihood ratio of the observed rewards (Lemma 18 of Kaufmann, Cappé, Garivier 2016,
generalized to non-stationary bandits).

## Indexing of the log-likelihood ratio

The `n`-th σ-algebra of `IT.filtration` is generated by the rounds `0, …, n` (the first `n + 1`
rounds), while `llrProcess ν ν' A Y n` sums the log-likelihood ratios of the rounds `0, …, n - 1`.
In the paper (rounds numbered from `1`), `𝓕_t` and `L_t` both cover the rounds `1, …, t`, so the
statement on this trajectory space is `P_ν'(E) = E_ν[1_E exp(-L_{σ + 1})]` (proved from
`Bandits.trajMeasure_banditSeq_apply_eq_setLIntegral_of_isStoppingTime`). The phase-1 statement,
with `L_σ` in place of `L_{σ + 1}`, was false: it fails already for the constant stopping time
`σ = 0` and the event `{Y_0 ∈ B} ∈ 𝓕_0`, whose left-hand side is the expected
`ν'_{0, X_0}`-probability of `B` and right-hand side the expected `ν_{0, X_0}`-probability of `B`.
-/

@[expose] public section

open MeasureTheory ProbabilityTheory Learning Real
open scoped ENNReal ENat

namespace MaynardZhang2026Complexity

variable {𝓐 : Type*} [Countable 𝓐] [MeasurableSpace 𝓐] [DiscreteMeasurableSpace 𝓐]

/-- **Lemma 6** (Maynard-Zhang, Xiong, Jamieson, Fazel 2026). Let `ν`, `ν'` be non-stationary
bandit models with mutually absolutely continuous reward distributions and `alg` an algorithm;
`P_ν`, `P_ν'` are the laws of the trajectory of `alg` under `ν` and `ν'`. For every stopping time
`σ` of the history filtration (finite everywhere) and every event `E ∈ 𝓕_σ`,
`P_ν'(E) = E_ν[1_E exp(-L_{σ + 1})]`: `𝓕_n` is generated by the rounds `0, …, n` and
`L_{n + 1}` is the log-likelihood ratio of these rounds (the paper's `L_σ`, rounds being numbered
from `1` there). The arms are countable (finitely many in the paper), so that the log-likelihood
ratio is jointly measurable in the arm and the reward. -/
theorem trajMeasure_eq_lintegral_exp_neg_llrProcess (alg : Algorithm Unit 𝓐 ℝ)
    (ν ν' : ℕ → Kernel 𝓐 ℝ) [∀ t, IsMarkovKernel (ν t)] [∀ t, IsMarkovKernel (ν' t)]
    (hac : ∀ t k, ν t k ≪ ν' t k) (hac' : ∀ t k, ν' t k ≪ ν t k)
    {σ : (ℕ → Round Unit 𝓐 ℝ) → ℕ∞} (hσ : IsStoppingTime (IT.filtration Unit 𝓐 ℝ) σ)
    (hfin : ∀ ω, σ ω ≠ ⊤)
    {S : Set (ℕ → Round Unit 𝓐 ℝ)} (hS : MeasurableSet[hσ.measurableSpace] S) :
    trajMeasure alg (Environment.banditSeq ν') S =
      ∫⁻ ω in S,
        ENNReal.ofReal (exp (-Bandits.llrProcess ν ν' IT.action IT.feedback ((σ ω).toNat + 1) ω))
        ∂(trajMeasure alg (Environment.banditSeq ν)) :=
  Bandits.trajMeasure_banditSeq_apply_eq_setLIntegral_of_isStoppingTime alg hac hac' hσ hfin hS

end MaynardZhang2026Complexity
