module

public import Mathlib.Analysis.Convex.Hull
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.LinearAlgebra.Matrix.SchurComplement
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Convex.Caratheodory
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.Algebra.Ring.Real
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.Analysis.Matrix.MeasurableSpace
public import Mathlib.Analysis.RCLike.Lemmas
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Mathlib.MeasureTheory.Order.Lattice
public import Mathlib.MeasureTheory.MeasurableSpace.Defs
public import Mathlib.Logic.Equiv.Defs
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.GroupTheory.Perm.Fin
public import Mathlib.Probability.ProbabilityMassFunction.Integrals
public import Mathlib.MeasureTheory.Measure.Prod
public import Mathlib.Probability.Distributions.Uniform
public import Mathlib.MeasureTheory.Integral.Prod
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Metric
public import Mathlib.CategoryTheory.Countable
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.MeasureTheory.Measure.LogLikelihoodRatio
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Probability.Martingale.BorelCantelli
public import Mathlib.Analysis.Convex.Exposed
public import Mathlib.Analysis.InnerProductSpace.Basic
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
public import Mathlib.Probability.Distributions.Gaussian.Real
public import Mathlib.Probability.Process.HittingTime
public import Mathlib.MeasureTheory.Constructions.Cylinders
public import Mathlib.MeasureTheory.Integral.Indicator
public import Mathlib.Probability.ConditionalProbability
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.IdentDistrib
public import Mathlib.MeasureTheory.Measure.Map
public import Mathlib.Probability.Kernel.Composition.Prod
public import Mathlib.Probability.Kernel.Composition.IntegralCompProd
public import Mathlib.Probability.Kernel.Composition.Lemmas
public import Mathlib.Probability.Kernel.Composition.MeasureCompProd
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Analysis.InnerProductSpace.Continuous
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Analysis.Normed.Group.Pointwise
public import Mathlib.Data.Fintype.Order
public import Mathlib.Topology.Order.Compact

/-! # Standalone extraction for `MaynardZhang2026Complexity.hasSubgaussianMGF_sum_perm`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace Matrix
end Matrix
namespace Learning
end Learning
namespace Finset
end Finset
namespace Equiv.Perm
end Equiv.Perm
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace MaynardZhang2026Complexity
end MaynardZhang2026Complexity

-- ═══ MaynardZhang2026Complexity.LeanMachineLearning.DesignMatrix ═══
@[expose] public section
open Matrix Real
open scoped RealInnerProductSpace
namespace Learning
variable {ι : Type*}

/-- The design matrix `x xᵀ` of a point `x`. -/
def outerSelf (x : EuclideanSpace ℝ ι) : Matrix ι ι ℝ :=
  Matrix.vecMulVec (WithLp.ofLp x) (WithLp.ofLp x)

variable [Fintype ι]
variable [DecidableEq ι]
variable {ι : Type*} {𝒳 : Set (EuclideanSpace ℝ ι)} {x : EuclideanSpace ℝ ι} {A : Matrix ι ι ℝ} {R : ℝ}
variable [Fintype ι]
variable [DecidableEq ι]
end Learning
end

-- ═══ MaynardZhang2026Complexity.Mathlib.Analysis.InnerProductSpace.Mahalanobis ═══
@[expose] public section
open Matrix
namespace Matrix
variable {ι : Type*} [Fintype ι]

/-- The squared Mahalanobis norm `‖x‖_A² = xᵀ A x`. -/
def mahalanobisSq (A : Matrix ι ι ℝ) (x : EuclideanSpace ℝ ι) : ℝ :=
  WithLp.ofLp x ⬝ᵥ A *ᵥ WithLp.ofLp x

end Matrix
end

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.Lattice ═══
@[expose] public section
open Finset
variable {α δ : Type*} [MeasurableSpace δ] [SemilatticeInf α] {m : MeasurableSpace α} [MeasurableInf₂ α]
attribute [to_dual existing] MeasurableInf₂
end

-- ═══ MaynardZhang2026Complexity.Mathlib.MeasureTheory.MeasurableSpace.Instances ═══
@[expose] public section
namespace Equiv.Perm
variable {α : Type*}

instance instMeasurableSpace : MeasurableSpace (Equiv.Perm α) := ⊤

end Equiv.Perm
end

-- ═══ MaynardZhang2026Complexity.MXJF2026.Lemma9 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Learning Matrix
open scoped RealInnerProductSpace
namespace MaynardZhang2026Complexity
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

set_option linter.unusedVariables false in
/-- **Lemma 9** (Maynard-Zhang, Xiong, Jamieson, Fazel 2026). Let `x_1, …, x_T` span `ℝ^d` with
`‖x_t‖ ≤ B`, `θ_1, …, θ_T` with `‖θ_t‖ ≤ M`, `θ̄_T = (1/T) ∑_t θ_t`, `A = ∑_t x_t x_tᵀ` and
`π` a uniformly random permutation of `[T]`. For every `z ∈ ℝ^d`,
`zᵀ ∑_t A⁻¹ x_t x_tᵀ (θ_{π(t)} - θ̄_T)` is `√8 M B ‖z‖_{A⁻¹}`-sub-Gaussian.

The spanning assumption `hspan` is not used by the proof. -/
@[nolint unusedArguments]
theorem hasSubgaussianMGF_sum_perm {T : ℕ} (x θ : Fin T → EuclideanSpace ℝ ι)
    (hspan : Submodule.span ℝ (Set.range x) = ⊤) {B M : ℝ} (hB : ∀ t, ‖x t‖ ≤ B)
    (hM : ∀ t, ‖θ t‖ ≤ M) (z : EuclideanSpace ℝ ι) :
    HasSubgaussianMGF (fun π : Equiv.Perm (Fin T) ↦
        ∑ t, ⟪z, Matrix.toEuclideanCLM (𝕜 := ℝ) (∑ s, outerSelf (x s))⁻¹ (x t)⟫ *
          ⟪x t, θ (π t) - (T : ℝ)⁻¹ • ∑ s, θ s⟫)
      (8 * M ^ 2 * B ^ 2 * mahalanobisSq (∑ s, outerSelf (x s))⁻¹ z).toNNReal
      (PMF.uniformOfFintype (Equiv.Perm (Fin T))).toMeasure := sorry

end MaynardZhang2026Complexity
end
