module

public import Mathlib.Analysis.Convex.Hull
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.LinearAlgebra.Matrix.SchurComplement
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Convex.Caratheodory
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.Algebra.Ring.Real
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.Analysis.Matrix.MeasurableSpace
public import Mathlib.Analysis.RCLike.Lemmas
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Process.HittingTime
public import Mathlib.MeasureTheory.Constructions.Cylinders
public import Mathlib.MeasureTheory.Integral.Indicator
public import Mathlib.Probability.ConditionalProbability
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.IdentDistrib
public import Mathlib.MeasureTheory.Measure.Map
public import Mathlib.Probability.Kernel.Composition.IntegralCompProd
public import Mathlib.Probability.Kernel.Composition.Lemmas
public import Mathlib.Probability.Kernel.Composition.MeasureCompProd
public import Mathlib.Probability.Kernel.Composition.Prod
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.MeasureTheory.Order.Lattice
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
public import Mathlib.Probability.Distributions.Gaussian.Real
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Probability.Martingale.BorelCantelli
public import Mathlib.MeasureTheory.Measure.LogLikelihoodRatio
public import Mathlib.CategoryTheory.Countable
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.Analysis.InnerProductSpace.Basic
public import Mathlib.Analysis.InnerProductSpace.Continuous
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Analysis.Normed.Group.Pointwise
public import Mathlib.Data.Fintype.Order
public import Mathlib.Topology.Order.Compact
public import Mathlib.Analysis.Convex.Exposed
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Metric
public import Mathlib.Probability.Distributions.Uniform
public import Mathlib.InformationTheory.KullbackLeibler.Basic
public import Mathlib.Analysis.Convex.Join
public import Mathlib.Analysis.Convex.KreinMilman
public import Mathlib.Analysis.InnerProductSpace.Dual
public import Mathlib.Analysis.LocallyConvex.Separation
public import Mathlib.Probability.Martingale.Convergence
public import Mathlib.InformationTheory.KullbackLeibler.DataProcessing
public import Mathlib.MeasureTheory.Function.ConditionalExpectation.RadonNikodym
public import Mathlib.InformationTheory.KullbackLeibler.ChainRule
public import Mathlib.Probability.Kernel.Composition.RadonNikodym
public import Mathlib.Probability.Kernel.Composition.AbsolutelyContinuous

/-! # Standalone extraction for `MaynardZhang2026Complexity.exists_minGapGE_le_max_error_optValue`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace Matrix
end Matrix
namespace Learning
end Learning
namespace Set
end Set
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Finset
end Finset
namespace Learning.IdentAlg
end Learning.IdentAlg
namespace Bandits.Linear
end Bandits.Linear
namespace MaynardZhang2026Complexity
end MaynardZhang2026Complexity
namespace InformationTheory
end InformationTheory

-- ═══ MaynardZhang2026Complexity.LeanMachineLearning.DesignMatrix ═══
@[expose] public section
open Matrix Real
open scoped RealInnerProductSpace
namespace Learning
variable {ι : Type*}

/-- The design matrix `x xᵀ` of a point `x`. -/
def outerSelf (x : EuclideanSpace ℝ ι) : Matrix ι ι ℝ :=
  Matrix.vecMulVec (WithLp.ofLp x) (WithLp.ofLp x)

variable [Fintype ι]
variable [DecidableEq ι]
variable {ι : Type*} {𝒳 : Set (EuclideanSpace ℝ ι)} {x : EuclideanSpace ℝ ι} {A : Matrix ι ι ℝ} {R : ℝ}
variable [Fintype ι]
variable [DecidableEq ι]
end Learning
end

-- ═══ MaynardZhang2026Complexity.LeanMachineLearning.Design ═══
@[expose] public section
open Real Filter Set
open scoped RealInnerProductSpace MatrixOrder Matrix Topology
namespace Learning
variable {ι : Type*} {𝒳 : Set (EuclideanSpace ℝ ι)} {w : EuclideanSpace ℝ ι →₀ ℝ} {A : Matrix ι ι ℝ} {x : EuclideanSpace ℝ ι}

/-- The design matrix `∑ₓ w x • x xᵀ` of finitely supported weights `w` on the space. -/
noncomputable def designMatrix : (EuclideanSpace ℝ ι →₀ ℝ) →ₗ[ℝ] Matrix ι ι ℝ :=
  Finsupp.linearCombination ℝ outerSelf

/-- A design distribution on `𝒳`: finitely supported nonnegative weights on points of `𝒳`
summing to one. -/
structure IsDesign (𝒳 : Set (EuclideanSpace ℝ ι)) (w : EuclideanSpace ℝ ι →₀ ℝ) : Prop where
  support_subset : ↑w.support ⊆ 𝒳
  nonneg : ∀ x, 0 ≤ w x
  sum_eq_one : ∑ x ∈ w.support, w x = 1

variable [Fintype ι]
variable [DecidableEq ι]
end Learning
end

-- ═══ MaynardZhang2026Complexity.Mathlib.Analysis.InnerProductSpace.Mahalanobis ═══
@[expose] public section
open Matrix
namespace Matrix
variable {ι : Type*} [Fintype ι]

/-- The squared Mahalanobis norm `‖x‖_A² = xᵀ A x`. -/
def mahalanobisSq (A : Matrix ι ι ℝ) (x : EuclideanSpace ℝ ι) : ℝ :=
  WithLp.ofLp x ⬝ᵥ A *ᵥ WithLp.ofLp x

end Matrix
end

-- ═══ LeanMachineLearning.SequentialLearning.Algorithm ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- One round of interaction: an observation, then an action, then a feedback. -/
abbrev Round (𝓞 𝓐 𝓨 : Type*) := 𝓞 × 𝓐 × 𝓨

/-- History of `n` complete rounds; `n = 0` is the empty history. -/
abbrev Hist (𝓞 𝓐 𝓨 : Type*) (n : ℕ) := Fin n → Round 𝓞 𝓐 𝓨

/-- A stochastic, sequential algorithm.
At each round, it sees an observation in `𝓞`, then takes an action in `𝓐`, and finally receives
feedback in `𝓨`. The action is a random function of the past rounds and the current observation. -/
@[ext]
structure Algorithm (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the action of round `n` given the past rounds and the current observation. -/
  policy : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓐
  /-- The policy is a Markov kernel. -/
  [isMarkovKernel_policy : ∀ n, IsMarkovKernel (policy n)]

/-- A stochastic environment.
At each round, an observation is drawn prior to the algorithm taking an action. Then the environment
provides feedback based on the observation and the action. -/
@[ext]
structure Environment (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the observation of round `n` given the past rounds. -/
  obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞
  /-- Law of the feedback of round `n` given the past rounds, the observation and the action. -/
  feedback : (n : ℕ) → Kernel ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) 𝓨
  /-- The observation kernel is a Markov kernel. -/
  [isMarkovKernel_obs : ∀ n, IsMarkovKernel (obs n)]
  /-- The feedback kernel is a Markov kernel. -/
  [isMarkovKernel_feedback : ∀ n, IsMarkovKernel (feedback n)]

section IsAlgEnvSeq
variable {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨} {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence before time `n`: the rounds at
times `0, ..., n - 1`. -/
def history (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ (O i ω, A i ω, Y i ω)

/-- An algorithm-environment sequence: a sequence of observations, actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The observation sequence is measurable. -/
  measurable_obs n : Measurable (O n) := by fun_prop
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The observation at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_obs n :
    HasCondDistrib (O n) (history O A Y n) (env.obs n) P
  /-- The action at time `n` has the correct conditional distribution given the history and the
  observation at time `n`. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (history O A Y n ω, O n ω)) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  observation and the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history O A Y n ω, O n ω), A n ω)) (env.feedback n) P

end IsAlgEnvSeq
end Learning
end

-- ═══ LeanMachineLearning.SequentialLearning.StoppedHistory ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω} {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨} {O : ℕ → Ω → 𝓞} {X : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {S : Set (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n)} {τ : Ω → WithTop ℕ} {ω : Ω} {n M : ℕ}

/-- The history of the first `n` rounds, as a history of variable length in the sigma type
`Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n`. -/
def sigmaHistory (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) :
    Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n :=
  ⟨n, history O X Y n ω⟩

end Learning
end

-- ═══ LeanMachineLearning.SequentialLearning.IdentificationAlg ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
open scoped ENat
namespace Learning
variable {𝓞 𝓐 𝓨 𝓓 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {m𝓓 : MeasurableSpace 𝓓} {mΩ : MeasurableSpace Ω} {O : ℕ → Ω → 𝓞} {X : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}

/-- An identification algorithm with outputs in `𝓓`: a sampling rule `alg`, a stopping rule
`stopSet` (the algorithm stops after `n` rounds if the history of these rounds belongs to
`stopSet`) and an output rule `output`, a Markov kernel giving the distribution of the output
given the history of the rounds played. -/
structure IdentAlg (𝓞 𝓐 𝓨 𝓓 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐]
    [MeasurableSpace 𝓨] [MeasurableSpace 𝓓] where
  /-- The sampling rule. -/
  alg : Algorithm 𝓞 𝓐 𝓨
  /-- The stopping rule: the algorithm stops after `n` rounds if the history of these rounds
  belongs to `stopSet`. -/
  stopSet : Set (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n)
  /-- The stopping rule is measurable. -/
  measurableSet_stopSet : MeasurableSet stopSet
  /-- The output rule: distribution of the output given the history of the rounds played. -/
  output : Kernel (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n) 𝓓
  /-- The output rule is a Markov kernel. -/
  [isMarkovKernel_output : IsMarkovKernel output]

namespace IdentAlg
variable {A : IdentAlg 𝓞 𝓐 𝓨 𝓓} {env : Environment 𝓞 𝓐 𝓨} {out : Ω → 𝓓} {P : Measure Ω}

/-- The stopping time of `A` on the observation, action and feedback processes `O`, `X`, `Y`: the
number of rounds played, that is the first `n` such that the history of the first `n` rounds
belongs to the stopping rule `A.stopSet` (`⊤` if there is none). -/
noncomputable def stoppingTime (A : IdentAlg 𝓞 𝓐 𝓨 𝓓)
    (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) :
    Ω → ℕ∞ :=
  hittingAfter (sigmaHistory O X Y) A.stopSet 0

/-- The history of the rounds played by an identification algorithm `A`, as a history of variable
length: the history stopped at `A.stoppingTime O X Y`
(the history of an arbitrary number of rounds if `A` never stops). -/
noncomputable def stoppedHist (A : IdentAlg 𝓞 𝓐 𝓨 𝓓)
    (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) :
    Ω → Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n :=
  stoppedValue (sigmaHistory O X Y) (A.stoppingTime O X Y)

/-- `(O, X, Y, out)` is a *run* of the identification algorithm `A` in the environment `env` on
the probability space `(Ω, P)`: the observation, action and feedback processes `O`, `X`, `Y` form
an algorithm-environment sequence for the sampling rule `A.alg` and `env`, and the output `out` has
conditional law `A.output` given the history at the stopping time. -/
structure IsRun (A : IdentAlg 𝓞 𝓐 𝓨 𝓓) (env : Environment 𝓞 𝓐 𝓨)
    (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (out : Ω → 𝓓)
    (P : Measure Ω := by volume_tac) [IsFiniteMeasure P] : Prop where
  /-- The actions and feedbacks are generated by the sampling rule in the environment. -/
  isAlgEnvSeq : IsAlgEnvSeq O X Y A.alg env P
  /-- The output is drawn from the output rule applied to the history at the stopping time. -/
  hasCondDistrib_output : HasCondDistrib out (A.stoppedHist O X Y) A.output P

end IdentAlg
end Learning
end

-- ═══ MaynardZhang2026Complexity.LeanMachineLearning.Identification.FixedBudget ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓐 𝓨 𝓓 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {m𝓓 : MeasurableSpace 𝓓} {mΩ : MeasurableSpace Ω} {O : ℕ → Ω → 𝓞} {X : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {P : Measure Ω}
namespace IdentAlg

/-- The identification algorithm `A` is *fixed-budget* with budget `T`: it stops after exactly
`T` rounds. -/
def IsFixedBudget (A : IdentAlg 𝓞 𝓐 𝓨 𝓓) (T : ℕ) : Prop := A.stopSet = {h | h.1 = T}

end IdentAlg
end Learning
end

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.Lattice ═══
@[expose] public section
open Finset
variable {α δ : Type*} [MeasurableSpace δ] [SemilatticeInf α] {m : MeasurableSpace α} [MeasurableInf₂ α]
attribute [to_dual existing] MeasurableInf₂
end

-- ═══ LeanMachineLearning.SequentialLearning.StationaryEnv ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨}

/-- An environment is oblivious if the distributions of the next observation and feedback
don't depend on the past history: the observation at time `n` has a fixed law, and the feedback
at time `n` depends only on the observation and the action at time `n`. -/
class Environment.IsOblivious (env : Environment 𝓞 𝓐 𝓨) : Prop where
  exists_obs_eq_const : ∃ μ : ℕ → Measure 𝓞, (∀ n, IsProbabilityMeasure (μ n)) ∧
    ∀ n, env.obs n = Kernel.const _ (μ n)
  exists_feedback_eq_comap : ∃ ν : ℕ → Kernel (𝓞 × 𝓐) 𝓨, (∀ n, IsMarkovKernel (ν n)) ∧
    ∀ n, env.feedback n = (ν n).comap (fun p ↦ (p.1.2, p.2)) (by fun_prop)

section Oblivious
variable {μ : ℕ → Measure 𝓞} [∀ n, IsProbabilityMeasure (μ n)] {ν : ℕ → Kernel (𝓞 × 𝓐) 𝓨} [∀ n, IsMarkovKernel (ν n)]

/-- The oblivious environment in which the observation at time `n` has law `μ n` and the feedback
at time `n` is drawn from `ν n` applied to the observation and the action at time `n`, whatever the
past history. -/
noncomputable
def Environment.oblivious (μ : ℕ → Measure 𝓞) [∀ n, IsProbabilityMeasure (μ n)]
    (ν : ℕ → Kernel (𝓞 × 𝓐) 𝓨) [∀ n, IsMarkovKernel (ν n)] : Environment 𝓞 𝓐 𝓨 where
  obs n := Kernel.const _ (μ n)
  feedback n := (ν n).comap (fun p ↦ (p.1.2, p.2)) (by fun_prop)

end Oblivious
section BanditSeq
variable {ν : ℕ → Kernel 𝓐 𝓨} [∀ n, IsMarkovKernel (ν n)]

/-- The oblivious environment without observations in which the feedback at time `n` is drawn from
`ν n` applied to the action at time `n`, whatever the past history. -/
noncomputable
def Environment.banditSeq (ν : ℕ → Kernel 𝓐 𝓨) [∀ n, IsMarkovKernel (ν n)] :
    Environment Unit 𝓐 𝓨 :=
  Environment.oblivious (fun _ ↦ Measure.dirac ()) (fun n ↦ (ν n).prodMkLeft Unit)

end BanditSeq
end Learning
end

-- ═══ MaynardZhang2026Complexity.LeanMachineLearning.Online.Bandit.Linear.Basic ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Learning
open scoped RealInnerProductSpace NNReal
namespace Bandits.Linear
variable {𝓐 E : Type*} [MeasurableSpace 𝓐] [NormedAddCommGroup E] [InnerProductSpace ℝ E]
section Kernel

/-- The reward kernel of the linear bandit with features `φ`, reward vector `θ` and noise law
`ξ`: playing `a` gives the feedback `⟪φ a, θ⟫ + ε` with `ε ∼ ξ`. -/
noncomputable def featureKernel (φ : 𝓐 → E) (θ : E) (ξ : Measure ℝ) : Kernel 𝓐 ℝ :=
  (Kernel.id ×ₖ Kernel.const 𝓐 ξ).map fun p ↦ ⟪φ p.1, θ⟫ + p.2

variable [MeasurableSpace E] [OpensMeasurableSpace E] {φ : 𝓐 → E}

lemma isMarkovKernel_featureKernel (hφ : Measurable φ) (θ : E) (ξ : Measure ℝ)
    [IsProbabilityMeasure ξ] : IsMarkovKernel (featureKernel φ θ ξ) := sorry

/-- The reward kernel of the linear bandit on the action set `𝒳 ⊆ E` with reward vector `θ` and
noise law `ξ`: playing `x ∈ 𝒳` gives the feedback `⟪x, θ⟫ + ε` with `ε ∼ ξ`. -/
noncomputable abbrev linearKernel (𝒳 : Set E) (θ : E) (ξ : Measure ℝ) : Kernel 𝒳 ℝ :=
  featureKernel (Subtype.val : 𝒳 → E) θ ξ

instance instIsMarkovKernelElemRealLinearKernelOfIsProbabilityMeasure (𝒳 : Set E) (θ : E) (ξ : Measure ℝ) [IsProbabilityMeasure ξ] :
    IsMarkovKernel (linearKernel 𝒳 θ ξ) :=
  isMarkovKernel_featureKernel measurable_subtype_coe θ ξ

end Kernel
section Environment
variable [MeasurableSpace E] [OpensMeasurableSpace E]

/-- The non-stationary linear environment on `𝒳` with reward vectors `θ t` and noise laws `ξ t`:
the oblivious environment in which the feedback of playing `x` at round `t` is `⟪x, θ t⟫ + ε_t`,
`ε_t ~ ξ t`. -/
noncomputable def nonstationaryLinearEnv (𝒳 : Set E) (θ : ℕ → E) (ξ : ℕ → Measure ℝ)
    [∀ t, IsProbabilityMeasure (ξ t)] : Environment Unit 𝒳 ℝ :=
  Environment.banditSeq fun t ↦ linearKernel 𝒳 (θ t) (ξ t)

end Environment
end Bandits.Linear
end

-- ═══ MaynardZhang2026Complexity.Mathlib.Analysis.Convex.Adjacent ═══
@[expose] public section
namespace Set
variable {E : Type*} [AddCommGroup E] [Module ℝ E] [TopologicalSpace E] {𝒳 : Set E} {x x' : E}

/-- The vertices of the convex hull of `𝒳`: its exposed points. -/
def vertices (𝒳 : Set E) : Set E := (convexHull ℝ 𝒳).exposedPoints ℝ

/-- The pairs of distinct vertices of the convex hull of `𝒳`. -/
def vertexPairs (𝒳 : Set E) : Set (E × E) := (vertices 𝒳).offDiag

end Set
end

-- ═══ MaynardZhang2026Complexity.MXJF2026.Setting ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Learning Bandits.Linear Matrix Set
open scoped RealInnerProductSpace
namespace MaynardZhang2026Complexity
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- The average parameter `θ̄_T = (1/T) ∑_{t < T} θ_t`. -/
noncomputable def avgParam (θ : ℕ → EuclideanSpace ℝ ι) (T : ℕ) : EuclideanSpace ℝ ι :=
  (T : ℝ)⁻¹ • ∑ t ∈ Finset.range T, θ t

/-- `x` is a hindsight best arm: `x ∈ 𝒳` maximizes `⟪·, θ̄_T⟫` over `𝒳`. -/
def IsBestArm (𝒳 : Set (EuclideanSpace ℝ ι)) (θ : ℕ → EuclideanSpace ℝ ι) (T : ℕ)
    (x : EuclideanSpace ℝ ι) : Prop :=
  x ∈ 𝒳 ∧ ∀ y ∈ 𝒳, ⟪y, avgParam θ T⟫ ≤ ⟪x, avgParam θ T⟫

/-- The parameter sequence `θ` has min-gap at least `Δ` over `T` rounds: some arm `x⋆ ∈ 𝒳`
beats every other vertex of `conv 𝒳` by at least `Δ` for `θ̄_T` (for `Δ > 0`, `x⋆` is then the
unique best arm). -/
def MinGapGE (𝒳 : Set (EuclideanSpace ℝ ι)) (θ : ℕ → EuclideanSpace ℝ ι) (T : ℕ) (Δ : ℝ) :
    Prop :=
  ∃ x ∈ 𝒳, ∀ y ∈ vertices 𝒳, y ≠ x → Δ ≤ ⟪x - y, avgParam θ T⟫

/-- The constraints of the inner optimization problem for the pair `(x, x')`: `x` beats every
other vertex by `Δ` for `θ`, and `x'` beats every other vertex by `Δ` for `θ + v`. -/
def PairFeasible (𝒳 : Set (EuclideanSpace ℝ ι)) (Δ : ℝ) (x x' θ v : EuclideanSpace ℝ ι) : Prop :=
  (∀ y ∈ vertices 𝒳, y ≠ x → Δ ≤ ⟪x - y, θ⟫) ∧ (∀ y ∈ vertices 𝒳, y ≠ x' → Δ ≤ ⟪x' - y, θ + v⟫)

/-- The value `min_{θ, v} vᵀ A v` of the inner optimization problem for the pair `(x, x')`,
subject to `PairFeasible 𝒳 Δ x x' θ v`. -/
noncomputable def pairValue (𝒳 : Set (EuclideanSpace ℝ ι)) (Δ : ℝ) (A : Matrix ι ι ℝ)
    (x x' : EuclideanSpace ℝ ι) : ℝ :=
  ⨅ q : {q : EuclideanSpace ℝ ι × EuclideanSpace ℝ ι // PairFeasible 𝒳 Δ x x' q.1 q.2},
    mahalanobisSq A q.1.2

/-- `f(𝒳, Δ) = max_{λ ∈ Δ_𝒳} min_{(x, x') ∈ 𝒴} min_{θ, v} vᵀ A(λ) v`, the optimization problem
of Lemma 3, over designs `λ` and pairs of distinct vertices. -/
noncomputable def optValue (𝒳 : Set (EuclideanSpace ℝ ι)) (Δ : ℝ) : ℝ :=
  ⨆ w : {w // IsDesign 𝒳 w}, ⨅ p : vertexPairs 𝒳,
    pairValue 𝒳 Δ (designMatrix (w : EuclideanSpace ℝ ι →₀ ℝ)) p.1.1 p.1.2

end MaynardZhang2026Complexity
end

-- ═══ MaynardZhang2026Complexity.MXJF2026.Lemma3 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory InformationTheory Learning Bandits.Linear Real Set Matrix
open scoped RealInnerProductSpace
universe u
namespace MaynardZhang2026Complexity
variable {ι : Type*} [Fintype ι]

/-- **Lemma 3** (optimization-based lower bound, Maynard-Zhang, Xiong, Jamieson, Fazel 2026).
Fix a finite arm set `𝒳 ⊆ ℝ^d` and `Δ > 0`. For every identification algorithm with
budget `T` there are parameter sequences `θ`, `θ'`, both with min-gap at least `Δ`, such that
`max(P_θ(x̂ ≠ x⋆), P_θ'(x̂ ≠ x⋆')) ≥ (1/4) exp(-T f(𝒳, Δ))`.

The paper leaves implicit that `T ≥ 1` and that `𝒳` has at least two points (for `T = 0` no
parameter sequence has min-gap `Δ > 0`; for a single arm `f(𝒳, Δ) = 0`, an infimum over no pairs,
while every algorithm is always right). The arm set need not span the space. -/
theorem exists_minGapGE_le_max_error_optValue (𝒳 : Finset (EuclideanSpace ℝ ι))
    (h𝒳 : 𝒳.Nontrivial) {Δ : ℝ} (hΔ : 0 < Δ) {T : ℕ} (hT : T ≠ 0)
    (A : IdentAlg Unit (𝒳 : Set (EuclideanSpace ℝ ι)) ℝ (𝒳 : Set (EuclideanSpace ℝ ι)))
    (hA : A.IsFixedBudget T) :
    ∃ θ θ' : ℕ → EuclideanSpace ℝ ι, MinGapGE 𝒳 θ T Δ ∧ MinGapGE 𝒳 θ' T Δ ∧
      ∀ {Ω : Type u} {_mΩ : MeasurableSpace Ω} (P : Measure Ω) [IsProbabilityMeasure P]
        (X : ℕ → Ω → 𝒳) (Y : ℕ → Ω → ℝ) (out : Ω → 𝒳)
        {Ω' : Type u} {_mΩ' : MeasurableSpace Ω'} (P' : Measure Ω') [IsProbabilityMeasure P']
        (X' : ℕ → Ω' → 𝒳) (Y' : ℕ → Ω' → ℝ) (out' : Ω' → 𝒳),
        A.IsRun (nonstationaryLinearEnv 𝒳 θ fun _ ↦ gaussianReal 0 1) (fun _ _ ↦ ()) X Y out P →
        A.IsRun (nonstationaryLinearEnv 𝒳 θ' fun _ ↦ gaussianReal 0 1) (fun _ _ ↦ ())
          X' Y' out' P' →
        1 / 4 * exp (-(T * optValue (𝒳 : Set (EuclideanSpace ℝ ι)) Δ)) ≤
          max (P.real {ω | ¬ IsBestArm 𝒳 θ T (out ω)})
            (P'.real {ω | ¬ IsBestArm 𝒳 θ' T (out' ω)}) := sorry

end MaynardZhang2026Complexity
end
