module

public import Mathlib.MeasureTheory.Order.Lattice
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.Analysis.Matrix.MeasurableSpace
public import Mathlib.Analysis.RCLike.Lemmas
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Mathlib.Analysis.Convex.Exposed
public import Mathlib.Analysis.InnerProductSpace.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Metric
public import Mathlib.CategoryTheory.Countable
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.MeasureTheory.Measure.LogLikelihoodRatio
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Probability.Martingale.BorelCantelli
public import Mathlib.Probability.Distributions.Uniform
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination
public import Mathlib.Analysis.Convex.Hull
public import Mathlib.LinearAlgebra.Matrix.SchurComplement
public import Mathlib.Analysis.Convex.Caratheodory
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.Algebra.Ring.Real
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
public import Mathlib.Probability.Distributions.Gaussian.Real
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.Probability.Process.HittingTime
public import Mathlib.MeasureTheory.Constructions.Cylinders
public import Mathlib.MeasureTheory.Integral.Indicator
public import Mathlib.Probability.ConditionalProbability
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.IdentDistrib
public import Mathlib.MeasureTheory.Measure.Map
public import Mathlib.Probability.Kernel.Composition.Prod
public import Mathlib.Probability.Kernel.Composition.IntegralCompProd
public import Mathlib.Probability.Kernel.Composition.Lemmas
public import Mathlib.Probability.Kernel.Composition.MeasureCompProd
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Analysis.InnerProductSpace.Continuous
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Analysis.Normed.Group.Pointwise
public import Mathlib.Data.Fintype.Order
public import Mathlib.Topology.Order.Compact

/-! # Standalone extraction for `MaynardZhang2026Complexity.ratio_le_iSup_adjacentTo`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace Finset
end Finset
namespace Matrix
end Matrix
namespace Set
end Set
namespace Learning
end Learning
namespace MaynardZhang2026Complexity
end MaynardZhang2026Complexity

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.Lattice ═══
@[expose] public section
open Finset
variable {α δ : Type*} [MeasurableSpace δ] [SemilatticeInf α] {m : MeasurableSpace α} [MeasurableInf₂ α]
attribute [to_dual existing] MeasurableInf₂
end

-- ═══ MaynardZhang2026Complexity.Mathlib.Analysis.InnerProductSpace.Mahalanobis ═══
@[expose] public section
open Matrix
namespace Matrix
variable {ι : Type*} [Fintype ι]

/-- The squared Mahalanobis norm `‖x‖_A² = xᵀ A x`. -/
def mahalanobisSq (A : Matrix ι ι ℝ) (x : EuclideanSpace ℝ ι) : ℝ :=
  WithLp.ofLp x ⬝ᵥ A *ᵥ WithLp.ofLp x

end Matrix
end

-- ═══ MaynardZhang2026Complexity.Mathlib.Analysis.Convex.Adjacent ═══
@[expose] public section
namespace Set
variable {E : Type*} [AddCommGroup E] [Module ℝ E] [TopologicalSpace E] {𝒳 : Set E} {x x' : E}

/-- The vertices of the convex hull of `𝒳`: its exposed points. -/
def vertices (𝒳 : Set E) : Set E := (convexHull ℝ 𝒳).exposedPoints ℝ

/-- Two distinct vertices `x`, `x'` of the convex hull of `𝒳` are *adjacent* if the segment
`[x, x']` is an exposed subset of the hull (an edge of the polytope). -/
def IsAdjacent (𝒳 : Set E) (x x' : E) : Prop :=
  x ∈ vertices 𝒳 ∧ x' ∈ vertices 𝒳 ∧ x ≠ x' ∧ IsExposed ℝ (convexHull ℝ 𝒳) (segment ℝ x x')

/-- The vertices adjacent to `x`. -/
def adjacentTo (𝒳 : Set E) (x : E) : Set E := {x' | IsAdjacent 𝒳 x x'}

end Set
end

-- ═══ MaynardZhang2026Complexity.MXJF2026.Lemma10 ═══
@[expose] public section
open Learning Matrix Set
open scoped RealInnerProductSpace
namespace MaynardZhang2026Complexity
variable {ι : Type*} [Fintype ι]

/-- **Lemma 10** (Maynard-Zhang, Xiong, Jamieson, Fazel 2026). Let `θ ∈ ℝ^d`, `M ≻ 0` and
`x⋆ = argmax_{x ∈ 𝒳} ⟪x, θ⟫` (unique). For every `x ∈ 𝒳 ∖ {x⋆}`,
`‖x⋆ - x‖²_M / ⟪x⋆ - x, θ⟫² ≤ max_{x' ∈ ℐ^{x⋆}} ‖x⋆ - x'‖²_M / ⟪x⋆ - x', θ⟫²`. -/
theorem ratio_le_iSup_adjacentTo (𝒳 : Finset (EuclideanSpace ℝ ι)) (θ : EuclideanSpace ℝ ι)
    {M : Matrix ι ι ℝ} (hM : M.PosDef) {xstar : EuclideanSpace ℝ ι} (hstar : xstar ∈ 𝒳)
    (hmax : ∀ y ∈ 𝒳, y ≠ xstar → ⟪y, θ⟫ < ⟪xstar, θ⟫) {x : EuclideanSpace ℝ ι} (hx : x ∈ 𝒳)
    (hne : x ≠ xstar) :
    mahalanobisSq M (xstar - x) / ⟪xstar - x, θ⟫ ^ 2 ≤
      ⨆ x' : adjacentTo (𝒳 : Set (EuclideanSpace ℝ ι)) xstar,
        mahalanobisSq M (xstar - x') / ⟪xstar - x', θ⟫ ^ 2 := sorry

end MaynardZhang2026Complexity
end
