module

public import Mathlib.MeasureTheory.Order.Lattice
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.Analysis.Matrix.MeasurableSpace
public import Mathlib.Analysis.RCLike.Lemmas
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Mathlib.Analysis.Convex.Exposed
public import Mathlib.Analysis.InnerProductSpace.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Metric
public import Mathlib.CategoryTheory.Countable
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.MeasureTheory.Measure.LogLikelihoodRatio
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Probability.Martingale.BorelCantelli
public import Mathlib.Probability.Distributions.Uniform
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination
public import Mathlib.Analysis.Convex.Hull
public import Mathlib.LinearAlgebra.Matrix.SchurComplement
public import Mathlib.Analysis.Convex.Caratheodory
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.Algebra.Ring.Real
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
public import Mathlib.Probability.Distributions.Gaussian.Real
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.Probability.Process.HittingTime
public import Mathlib.MeasureTheory.Constructions.Cylinders
public import Mathlib.MeasureTheory.Integral.Indicator
public import Mathlib.Probability.ConditionalProbability
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.IdentDistrib
public import Mathlib.MeasureTheory.Measure.Map
public import Mathlib.Probability.Kernel.Composition.Prod
public import Mathlib.Probability.Kernel.Composition.IntegralCompProd
public import Mathlib.Probability.Kernel.Composition.Lemmas
public import Mathlib.Probability.Kernel.Composition.MeasureCompProd
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Analysis.InnerProductSpace.Continuous
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Analysis.Normed.Group.Pointwise
public import Mathlib.Data.Fintype.Order
public import Mathlib.Topology.Order.Compact

/-! # Standalone extraction for `MaynardZhang2026Complexity.le_pairValue`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace Finset
end Finset
namespace Matrix
end Matrix
namespace Set
end Set
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace Bandits.Linear
end Bandits.Linear
namespace MaynardZhang2026Complexity
end MaynardZhang2026Complexity

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.Lattice ═══
@[expose] public section
open Finset
variable {α δ : Type*} [MeasurableSpace δ] [SemilatticeInf α] {m : MeasurableSpace α} [MeasurableInf₂ α]
attribute [to_dual existing] MeasurableInf₂
end

-- ═══ MaynardZhang2026Complexity.Mathlib.Analysis.InnerProductSpace.Mahalanobis ═══
@[expose] public section
open Matrix
namespace Matrix
variable {ι : Type*} [Fintype ι]

/-- The squared Mahalanobis norm `‖x‖_A² = xᵀ A x`. -/
def mahalanobisSq (A : Matrix ι ι ℝ) (x : EuclideanSpace ℝ ι) : ℝ :=
  WithLp.ofLp x ⬝ᵥ A *ᵥ WithLp.ofLp x

end Matrix
end

-- ═══ MaynardZhang2026Complexity.Mathlib.Analysis.Convex.Adjacent ═══
@[expose] public section
namespace Set
variable {E : Type*} [AddCommGroup E] [Module ℝ E] [TopologicalSpace E] {𝒳 : Set E} {x x' : E}

/-- The vertices of the convex hull of `𝒳`: its exposed points. -/
def vertices (𝒳 : Set E) : Set E := (convexHull ℝ 𝒳).exposedPoints ℝ

/-- The pairs of distinct vertices of the convex hull of `𝒳`. -/
def vertexPairs (𝒳 : Set E) : Set (E × E) := (vertices 𝒳).offDiag

end Set
end

-- ═══ MaynardZhang2026Complexity.MXJF2026.Setting ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Learning Bandits.Linear Matrix Set
open scoped RealInnerProductSpace
namespace MaynardZhang2026Complexity
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- The average parameter `θ̄_T = (1/T) ∑_{t < T} θ_t`. -/
noncomputable def avgParam (θ : ℕ → EuclideanSpace ℝ ι) (T : ℕ) : EuclideanSpace ℝ ι :=
  (T : ℝ)⁻¹ • ∑ t ∈ Finset.range T, θ t

/-- `x` is a hindsight best arm: `x ∈ 𝒳` maximizes `⟪·, θ̄_T⟫` over `𝒳`. -/
def IsBestArm (𝒳 : Set (EuclideanSpace ℝ ι)) (θ : ℕ → EuclideanSpace ℝ ι) (T : ℕ)
    (x : EuclideanSpace ℝ ι) : Prop :=
  x ∈ 𝒳 ∧ ∀ y ∈ 𝒳, ⟪y, avgParam θ T⟫ ≤ ⟪x, avgParam θ T⟫

/-- The constraints of the inner optimization problem for the pair `(x, x')`: `x` beats every
other vertex by `Δ` for `θ`, and `x'` beats every other vertex by `Δ` for `θ + v`. -/
def PairFeasible (𝒳 : Set (EuclideanSpace ℝ ι)) (Δ : ℝ) (x x' θ v : EuclideanSpace ℝ ι) : Prop :=
  (∀ y ∈ vertices 𝒳, y ≠ x → Δ ≤ ⟪x - y, θ⟫) ∧ (∀ y ∈ vertices 𝒳, y ≠ x' → Δ ≤ ⟪x' - y, θ + v⟫)

/-- The value `min_{θ, v} vᵀ A v` of the inner optimization problem for the pair `(x, x')`,
subject to `PairFeasible 𝒳 Δ x x' θ v`. -/
noncomputable def pairValue (𝒳 : Set (EuclideanSpace ℝ ι)) (Δ : ℝ) (A : Matrix ι ι ℝ)
    (x x' : EuclideanSpace ℝ ι) : ℝ :=
  ⨅ q : {q : EuclideanSpace ℝ ι × EuclideanSpace ℝ ι // PairFeasible 𝒳 Δ x x' q.1 q.2},
    mahalanobisSq A q.1.2

end MaynardZhang2026Complexity
end

-- ═══ MaynardZhang2026Complexity.MXJF2026.Lemma7 ═══
@[expose] public section
open Learning Matrix Set
open scoped RealInnerProductSpace
namespace MaynardZhang2026Complexity
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- **Lemma 7** (Maynard-Zhang, Xiong, Jamieson, Fazel 2026). For a positive definite matrix
`A` and a pair of distinct vertices `(x, x')`,
`min {vᵀ A v | (θ, v) feasible for (x, x')} ≥ 4 Δ² / ‖x - x'‖²_{A⁻¹}`. -/
theorem le_pairValue (𝒳 : Finset (EuclideanSpace ℝ ι)) {Δ : ℝ} (hΔ : 0 < Δ)
    {A : Matrix ι ι ℝ} (hA : A.PosDef)
    {x x' : EuclideanSpace ℝ ι} (hxx' : (x, x') ∈ vertexPairs (𝒳 : Set (EuclideanSpace ℝ ι))) :
    4 * Δ ^ 2 / mahalanobisSq A⁻¹ (x - x') ≤ pairValue 𝒳 Δ A x x' := sorry

end MaynardZhang2026Complexity
end
