module

public import Mathlib.Analysis.Convex.Hull
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.LinearAlgebra.Matrix.SchurComplement
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Convex.Caratheodory
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.Algebra.Ring.Real
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.Analysis.Matrix.MeasurableSpace
public import Mathlib.Analysis.RCLike.Lemmas
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Mathlib.MeasureTheory.Order.Lattice
public import Mathlib.Analysis.Convex.Exposed
public import Mathlib.Analysis.InnerProductSpace.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Metric
public import Mathlib.CategoryTheory.Countable
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.MeasureTheory.Measure.LogLikelihoodRatio
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Probability.Martingale.BorelCantelli
public import Mathlib.Probability.Distributions.Uniform
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
public import Mathlib.Probability.Distributions.Gaussian.Real
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.Probability.Process.HittingTime
public import Mathlib.MeasureTheory.Constructions.Cylinders
public import Mathlib.MeasureTheory.Integral.Indicator
public import Mathlib.Probability.ConditionalProbability
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.IdentDistrib
public import Mathlib.MeasureTheory.Measure.Map
public import Mathlib.Probability.Kernel.Composition.Prod
public import Mathlib.Probability.Kernel.Composition.IntegralCompProd
public import Mathlib.Probability.Kernel.Composition.Lemmas
public import Mathlib.Probability.Kernel.Composition.MeasureCompProd
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Analysis.InnerProductSpace.Continuous
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Analysis.Normed.Group.Pointwise
public import Mathlib.Data.Fintype.Order
public import Mathlib.Topology.Order.Compact
public import Mathlib.Analysis.Convex.Join
public import Mathlib.Analysis.Convex.KreinMilman
public import Mathlib.Analysis.InnerProductSpace.Dual
public import Mathlib.Analysis.LocallyConvex.Separation

/-! # Standalone extraction for `MaynardZhang2026Complexity.iInf_iSup_ratio_eq`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace Matrix
end Matrix
namespace Learning
end Learning
namespace Set
end Set
namespace Finset
end Finset
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Bandits.Linear
end Bandits.Linear
namespace MaynardZhang2026Complexity
end MaynardZhang2026Complexity

-- ═══ MaynardZhang2026Complexity.LeanMachineLearning.DesignMatrix ═══
@[expose] public section
open Matrix Real
open scoped RealInnerProductSpace
namespace Learning
variable {ι : Type*}

/-- The design matrix `x xᵀ` of a point `x`. -/
def outerSelf (x : EuclideanSpace ℝ ι) : Matrix ι ι ℝ :=
  Matrix.vecMulVec (WithLp.ofLp x) (WithLp.ofLp x)

variable [Fintype ι]
variable [DecidableEq ι]
variable {ι : Type*} {𝒳 : Set (EuclideanSpace ℝ ι)} {x : EuclideanSpace ℝ ι} {A : Matrix ι ι ℝ} {R : ℝ}
variable [Fintype ι]
variable [DecidableEq ι]
end Learning
end

-- ═══ MaynardZhang2026Complexity.LeanMachineLearning.Design ═══
@[expose] public section
open Real Filter Set
open scoped RealInnerProductSpace MatrixOrder Matrix Topology
namespace Learning
variable {ι : Type*} {𝒳 : Set (EuclideanSpace ℝ ι)} {w : EuclideanSpace ℝ ι →₀ ℝ} {A : Matrix ι ι ℝ} {x : EuclideanSpace ℝ ι}

/-- The design matrix `∑ₓ w x • x xᵀ` of finitely supported weights `w` on the space. -/
noncomputable def designMatrix : (EuclideanSpace ℝ ι →₀ ℝ) →ₗ[ℝ] Matrix ι ι ℝ :=
  Finsupp.linearCombination ℝ outerSelf

/-- A design distribution on `𝒳`: finitely supported nonnegative weights on points of `𝒳`
summing to one. -/
structure IsDesign (𝒳 : Set (EuclideanSpace ℝ ι)) (w : EuclideanSpace ℝ ι →₀ ℝ) : Prop where
  support_subset : ↑w.support ⊆ 𝒳
  nonneg : ∀ x, 0 ≤ w x
  sum_eq_one : ∑ x ∈ w.support, w x = 1

variable [Fintype ι]
variable [DecidableEq ι]
end Learning
end

-- ═══ MaynardZhang2026Complexity.Mathlib.Analysis.InnerProductSpace.Mahalanobis ═══
@[expose] public section
open Matrix
namespace Matrix
variable {ι : Type*} [Fintype ι]

/-- The squared Mahalanobis norm `‖x‖_A² = xᵀ A x`. -/
def mahalanobisSq (A : Matrix ι ι ℝ) (x : EuclideanSpace ℝ ι) : ℝ :=
  WithLp.ofLp x ⬝ᵥ A *ᵥ WithLp.ofLp x

end Matrix
end

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.Lattice ═══
@[expose] public section
open Finset
variable {α δ : Type*} [MeasurableSpace δ] [SemilatticeInf α] {m : MeasurableSpace α} [MeasurableInf₂ α]
attribute [to_dual existing] MeasurableInf₂
end

-- ═══ MaynardZhang2026Complexity.Mathlib.Analysis.Convex.Adjacent ═══
@[expose] public section
namespace Set
variable {E : Type*} [AddCommGroup E] [Module ℝ E] [TopologicalSpace E] {𝒳 : Set E} {x x' : E}

/-- The vertices of the convex hull of `𝒳`: its exposed points. -/
def vertices (𝒳 : Set E) : Set E := (convexHull ℝ 𝒳).exposedPoints ℝ

/-- Two distinct vertices `x`, `x'` of the convex hull of `𝒳` are *adjacent* if the segment
`[x, x']` is an exposed subset of the hull (an edge of the polytope). -/
def IsAdjacent (𝒳 : Set E) (x x' : E) : Prop :=
  x ∈ vertices 𝒳 ∧ x' ∈ vertices 𝒳 ∧ x ≠ x' ∧ IsExposed ℝ (convexHull ℝ 𝒳) (segment ℝ x x')

/-- The vertices adjacent to `x`. -/
def adjacentTo (𝒳 : Set E) (x : E) : Set E := {x' | IsAdjacent 𝒳 x x'}

end Set
end

-- ═══ MaynardZhang2026Complexity.MXJF2026.Setting ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Learning Bandits.Linear Matrix Set
open scoped RealInnerProductSpace
namespace MaynardZhang2026Complexity
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- The design distributions on `𝒳` with positive definite design matrix. -/
def PosDefDesign (𝒳 : Set (EuclideanSpace ℝ ι)) : Set (EuclideanSpace ℝ ι →₀ ℝ) :=
  {w | IsDesign 𝒳 w ∧ (designMatrix w).PosDef}

end MaynardZhang2026Complexity
end

-- ═══ MaynardZhang2026Complexity.MXJF2026.Proposition1 ═══
@[expose] public section
open Learning Matrix Set
open scoped RealInnerProductSpace
namespace MaynardZhang2026Complexity
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- **Proposition 1** (Maynard-Zhang, Xiong, Jamieson, Fazel 2026). For a finite
`𝒳 ⊆ ℝ^d`, `θ ∈ ℝ^d` with unique best arm `x⋆`,
`min_λ max_{x ∈ 𝒳 ∖ {x⋆}} ‖x⋆ - x‖²_{A(λ)⁻¹} / ⟪x⋆ - x, θ⟫²
  = min_λ max_{x ∈ ℐ^{x⋆}} ‖x⋆ - x‖²_{A(λ)⁻¹} / ⟪x⋆ - x, θ⟫²`,
the minima being over designs with positive definite design matrix. The paper's standing
assumption that `𝒳` spans `ℝ^d` is not needed (without it both sides are `0`, infima over no
designs). -/
theorem iInf_iSup_ratio_eq (𝒳 : Finset (EuclideanSpace ℝ ι))
    (θ : EuclideanSpace ℝ ι)
    {xstar : EuclideanSpace ℝ ι} (hstar : xstar ∈ 𝒳)
    (hmax : ∀ y ∈ 𝒳, y ≠ xstar → ⟪y, θ⟫ < ⟪xstar, θ⟫) :
    (⨅ w : PosDefDesign (𝒳 : Set (EuclideanSpace ℝ ι)), ⨆ x : {x // x ∈ 𝒳 ∧ x ≠ xstar},
        mahalanobisSq (designMatrix (w : EuclideanSpace ℝ ι →₀ ℝ))⁻¹ (xstar - x) /
          ⟪xstar - x, θ⟫ ^ 2) =
      ⨅ w : PosDefDesign (𝒳 : Set (EuclideanSpace ℝ ι)),
        ⨆ x : adjacentTo (𝒳 : Set (EuclideanSpace ℝ ι)) xstar,
          mahalanobisSq (designMatrix (w : EuclideanSpace ℝ ι →₀ ℝ))⁻¹ (xstar - x) /
            ⟪xstar - x, θ⟫ ^ 2 := sorry

end MaynardZhang2026Complexity
end
